import type { MetaFunction } from "@remix-run/node";
import { useEffect } from "react";
import "datatables.net-bs5"; // Import Bootstrap 5 DataTables
import DataTable from "datatables.net";

export const meta: MetaFunction = () => {
  return [
    { title: "Unidentified Persons" },
    { name: "description", content: "Welcome to FindMe!" },
  ];
};

export default function UnidentifiedPersonsTable() {
  useEffect(() => {
    // Initialize DataTable once the component mounts
    const table = new DataTable("#unidentifiedPersonsTable", {
      paging: true,
      autoWidth: false,
    });
    return () => {
      table.destroy();
    }; // Cleanup when unmounting
  }, []);

  return (
    <div className="container mt-5">
      <div className="table-responsive"> {/* Ensures the table is scrollable on small screens */}
      <h2 className="mt-5">Unidentifed Persons</h2>
      <table id="unidentifiedPersonsTable" className="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Case #</th>
            <th>Legal Last Name</th>
            <th>Legal First Name</th>
            <th>Missing Age</th>
            <th>Gender</th>
            <th>Town</th>
            <th>Date of Last Contact</th>
            <th>Date Modified</th>
          </tr>
        </thead>
        <tbody>
          {/* Sample Row */}
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>James</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>

          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>

          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>

          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>

          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>
          <tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr><tr>
            <td>001</td>
            <td>Doe</td>
            <td>John</td>
            <td>30</td>
            <td>Male</td>
            <td>Nairobi</td>
            <td>01/03/2024</td>
            <td>05/03/2024</td>
          </tr>

          

          
        </tbody>
      </table>
      </div>
    </div>
  );
}


